SELECT generate_series(1,100) AS id; -- generate_series ÄR EN INBYGGD FUNKTION. GER 1-100 (I EN OCH SAMMA RAD I DETTA FALL) 1 = STARTVÄRDET. SKRKV 5 OCH DET BÖRJAR FRÅN 5

SELECT UNNEST (generate_series(1,100)) AS id; -- 1 - 100, VARJE SIFFRA HAR SIN EGEN RAD

SELECT RANDOM(); -- GER ETT RANDOM VÄRDE MELLAN 0-1

SELECT FLOOR(RANDOM()*6+1); -- SKAPAR ETT RANDOMVÄRDE MELLAN 0-1, TAR DET *6 OCH + 1, SEN AVRUNDAR NEDÅT (FLOOR). DET BLIR TÄRNINGSKAST

SELECT FLOOR(RANDOM()*6+1) AS dice FROM generate_series(100); -- ANVÄNDER generate_series 100 GGR, SÅ DET BLIR SOM 100 TÄRNINGSKAST

SELECT
	UNNEST (generate_series(100)) AS id, -- SE RAD 1
	'student_' || id AS student, -- KOLUMN 2 HETER STUDENT, OCH VARJE STUDENT HETER STUDENT_ OCH KONKTAINERAR MED VÄRDET I id ( || KONKATINERAR)
	ROUND(RANDOM()* 100) AS score;
	
SELECT -- (2) SEN KÖRS DESSA (INKL CASE WHEN)
	id,
	'student_' || id AS student,
	score,
	CASE 
		WHEN score < 50 THEN 'F'
		WHEN score < 75 THEN 'G'
		ELSE 'VG'
	END AS grade
FROM ( -- (1) FROM CLAUSE KÖRS FÖRST, SÅ FÖRST SKAPAS 1-100 UNDER KOLUMN id, SEN SKAPAS score. 
	SELECT
	UNNEST (generate_series(100)) AS id,
	ROUND(RANDOM()* 100) AS score);
